apiVersion: v1
kind: ConfigMap
metadata:
  name: main-py-configmap
data:
  main.py: |
    from flask import Flask
    import os

    app = Flask(__name__)

    @app.route("/")
    def hello():
        api_key = os.environ.get("API_KEY")
        return f"Hello World! The API key is {api_key}"

    if __name__ == "__main__":
        app.run(host="0.0.0.0")
		
---

apiVersion: v1
kind: Secret
metadata:
  name: api-key-secret
type: Opaque
data:
  api-key: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: tiangolo/uwsgi-nginx-flask:python3.7
          ports:
            - containerPort: 80
          env:
            - name: FLASK_APP
              value: main.py
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key-secret
                  key: api-key
          volumeMounts:
            - name: main-py-volume
              mountPath: /app/main.py
              subPath: main.py
      volumes:
        - name: main-py-volume
          configMap:
            name: main-py-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP